name: Test

on:
  push: {}
  pull_request: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
        # with:
        #   submodules: true
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Update NPM
        # we use package-lock.json v2, which doesn't work well in NPM 6
        run: npm install -g npm@latest
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm test
